/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface WebBusinessCard {
    'email': string;
    'jobPosition': string;
    'name': string;
    'phone': string;
    'website': string;
  }
  interface WebBusinessCardAttributes extends StencilHTMLAttributes {
    'email'?: string;
    'jobPosition'?: string;
    'name'?: string;
    'phone'?: string;
    'website'?: string;
  }

  interface WebCountriesFinder {
    'keyword': string;
  }
  interface WebCountriesFinderAttributes extends StencilHTMLAttributes {
    'keyword'?: string;
  }

  interface WebComponentHello {
    'firstName': string;
    'websiteURL': string;
  }
  interface WebComponentHelloAttributes extends StencilHTMLAttributes {
    'firstName'?: string;
    'websiteURL'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'WebBusinessCard': Components.WebBusinessCard;
    'WebCountriesFinder': Components.WebCountriesFinder;
    'WebComponentHello': Components.WebComponentHello;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'web-business-card': Components.WebBusinessCardAttributes;
    'web-countries-finder': Components.WebCountriesFinderAttributes;
    'web-component-hello': Components.WebComponentHelloAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLWebBusinessCardElement extends Components.WebBusinessCard, HTMLStencilElement {}
  var HTMLWebBusinessCardElement: {
    prototype: HTMLWebBusinessCardElement;
    new (): HTMLWebBusinessCardElement;
  };

  interface HTMLWebCountriesFinderElement extends Components.WebCountriesFinder, HTMLStencilElement {}
  var HTMLWebCountriesFinderElement: {
    prototype: HTMLWebCountriesFinderElement;
    new (): HTMLWebCountriesFinderElement;
  };

  interface HTMLWebComponentHelloElement extends Components.WebComponentHello, HTMLStencilElement {}
  var HTMLWebComponentHelloElement: {
    prototype: HTMLWebComponentHelloElement;
    new (): HTMLWebComponentHelloElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'web-business-card': HTMLWebBusinessCardElement
    'web-countries-finder': HTMLWebCountriesFinderElement
    'web-component-hello': HTMLWebComponentHelloElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'web-business-card': HTMLWebBusinessCardElement;
    'web-countries-finder': HTMLWebCountriesFinderElement;
    'web-component-hello': HTMLWebComponentHelloElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
